/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sprint;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramso
 */
public class EditarElemento extends javax.swing.JFrame {

    /**
     * Creates new form EditarElemento
     */
    public EditarElemento() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Lista elementos funcionales");
        switch(VentanListarElementos.elemento[0].toString()){
            case "EE": tiposE.setSelectedIndex(1); break;
            case "SE": tiposE.setSelectedIndex(2); break;
            case "CE": tiposE.setSelectedIndex(3); break;
            case "FLI": tiposE.setSelectedIndex(4); break;
            case "FLE": tiposE.setSelectedIndex(5); break;
        }
        if (VentanListarElementos.elemento[0].equals("EE")) {
            je3.setVisible(true);
            input3.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);
            je4.setVisible(false);
            input4.setVisible(false);
            
            input1.setText(VentanListarElementos.elemento[1]);
            input5.setText(VentanListarElementos.elemento[2]);
            input3.setText(VentanListarElementos.elemento[4]);
        } else if (VentanListarElementos.elemento[0].matches("SE|CE")) {
            je2.setVisible(true);
            input2.setVisible(true);
            je3.setVisible(false);
            input3.setVisible(false);
            je4.setVisible(false);
            input4.setVisible(false);
            
            input1.setText(VentanListarElementos.elemento[1]);
            input5.setText(VentanListarElementos.elemento[2]);
            input2.setText(VentanListarElementos.elemento[3]);
        } else if (VentanListarElementos.elemento[0].matches("FLI|FLE")) {
            je4.setVisible(true);
            input4.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);
            je3.setVisible(false);
            input3.setVisible(false);
            
            input1.setText(VentanListarElementos.elemento[1]);
            input5.setText(VentanListarElementos.elemento[2]);
            input4.setText(VentanListarElementos.elemento[5]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiposE = new javax.swing.JComboBox<>();
        input1 = new javax.swing.JTextField();
        je1 = new javax.swing.JLabel();
        je2 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        je3 = new javax.swing.JLabel();
        je4 = new javax.swing.JLabel();
        input4 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        je5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elemento funcional:");

        tiposE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar tipo", "EE", "SE", "CE", "FLI", "FLE" }));
        tiposE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposEActionPerformed(evt);
            }
        });

        je1.setText("Nombre:");

        je2.setText("Nº Ficheros  Referenciados:");

        je3.setText("Nº Ficheros  Relacionados");

        je4.setText("Nº Tipos de Registros");

        je5.setText("Nº  Datos Elementales:");

        jButton2.setText("Guardar cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarLayout = new javax.swing.GroupLayout(editar);
        editar.setLayout(editarLayout);
        editarLayout.setHorizontalGroup(
            editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarLayout.createSequentialGroup()
                        .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(je1)
                            .addComponent(jLabel1)
                            .addComponent(je2)
                            .addComponent(je4)
                            .addComponent(je5)
                            .addComponent(je3))
                        .addGap(48, 48, 48)
                        .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiposE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(137, 137, 137))))
        );
        editarLayout.setVerticalGroup(
            editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tiposE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je1)
                    .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(je2)
                    .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(je3)
                    .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je4)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je5)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiposEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposEActionPerformed
        // TODO add your handling code here:

        if (tiposE.getSelectedItem().toString().equals("EE")) {
            je3.setVisible(true);
            input3.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);

            je4.setVisible(false);
            input4.setVisible(false);
        } else if (tiposE.getSelectedItem().toString().matches("SE|CE")) {
            je2.setVisible(true);
            input2.setVisible(true);

            je3.setVisible(false);
            input3.setVisible(false);
            je4.setVisible(false);
            input4.setVisible(false);
        } else if (tiposE.getSelectedItem().toString().matches("FLI|FLE")) {
            je4.setVisible(true);
            input4.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);
            je3.setVisible(false);
            input3.setVisible(false);
        }
    }//GEN-LAST:event_tiposEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: guardar
        if (tiposE.getSelectedItem().toString().equals("EE")) {
            if (!input3.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                //ven.setVisible(true);
                //ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input3.getText());
                VentanListarElementos.modelo.setValueAt(tiposE.getSelectedItem().toString(), VentanListarElementos.posRow, 0);
                VentanListarElementos.modelo.setValueAt(input1.getText(), VentanListarElementos.posRow, 1);
                VentanListarElementos.modelo.setValueAt(input5.getText(), VentanListarElementos.posRow, 2);
                VentanListarElementos.modelo.setValueAt(input3.getText(), VentanListarElementos.posRow, 4);
                
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 3);
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 5);
            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        if (tiposE.getSelectedItem().toString().matches("SE|CE")) {
            if (!input2.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                //ven.setVisible(true);
                //ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input2.getText());
                VentanListarElementos.modelo.setValueAt(tiposE.getSelectedItem().toString(), VentanListarElementos.posRow, 0);
                VentanListarElementos.modelo.setValueAt(input1.getText(), VentanListarElementos.posRow, 1);
                VentanListarElementos.modelo.setValueAt(input5.getText(), VentanListarElementos.posRow, 2);
                VentanListarElementos.modelo.setValueAt(input2.getText(), VentanListarElementos.posRow, 3);
                
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 4);
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 5);
            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        if (tiposE.getSelectedItem().toString().matches("FLI|FLE")) {
            if (!input4.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                //ven.setVisible(true);
                //ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input4.getText());
                VentanListarElementos.modelo.setValueAt(tiposE.getSelectedItem().toString(), VentanListarElementos.posRow, 0);
                VentanListarElementos.modelo.setValueAt(input1.getText(), VentanListarElementos.posRow, 1);
                VentanListarElementos.modelo.setValueAt(input5.getText(), VentanListarElementos.posRow, 2);
                VentanListarElementos.modelo.setValueAt(input4.getText(), VentanListarElementos.posRow, 5);
                
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 3);
                VentanListarElementos.modelo.setValueAt("--", VentanListarElementos.posRow, 4);
            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarElemento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editar;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel je1;
    private javax.swing.JLabel je2;
    private javax.swing.JLabel je3;
    private javax.swing.JLabel je4;
    private javax.swing.JLabel je5;
    private javax.swing.JComboBox<String> tiposE;
    // End of variables declaration//GEN-END:variables
}
