/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sprint;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhony
 */
public class VentanaComplejidad extends javax.swing.JFrame {

    DefaultTableModel modeloC;

    public VentanaComplejidad() {
        initComponents();
        setLocationRelativeTo(null);
        modeloC = new DefaultTableModel();
        modeloC.addColumn("Descripción");
        modeloC.addColumn("Sencilla");
        modeloC.addColumn("Media");
        modeloC.addColumn("Compleja");
        modeloC.addRow(new Object[]{"Nº Entradas Externas", 0, 0, 0});
        modeloC.addRow(new Object[]{"Nº Salidas Externas", 0, 0, 0});
        modeloC.addRow(new Object[]{"Nº Grupos Lógicos de Datos Internos ", 0, 0, 0});
        modeloC.addRow(new Object[]{"Nº Grupos Lógicos de Datos de Interfaz", 0, 0, 0});
        modeloC.addRow(new Object[]{"Nº Consultas Externas", 0, 0, 0});
        this.tablaC.setModel(modeloC);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaComplejidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaC;
    // End of variables declaration//GEN-END:variables

    void añadirComplejidad(String tipo, String complejidad) {
        if (tipo.equals("EE")) {
            if (complejidad.equals("S")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(0, 1) + 1), 0, 1);
            } else if (complejidad.equals("M")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(0, 2) + 1), 0, 2);
            } else if (complejidad.equals("C")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(0, 3) + 1), 0, 3);
            }
        }
        if (tipo.equals("SE")) {
            if (complejidad.equals("S")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(1, 1) + 1), 1, 1);
            } else if (complejidad.equals("M")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(1, 2) + 1), 1, 2);
            } else if (complejidad.equals("C")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(1, 3) + 1), 1, 3);
            }
        }
        if (tipo.equals("FLI")) {
            if (complejidad.equals("S")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(2, 1) + 1), 2, 1);
            } else if (complejidad.equals("M")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(2, 2) + 1), 2, 2);
            } else if (complejidad.equals("C")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(2, 3) + 1), 2, 3);
            }
        }
        if (tipo.equals("FLE")) {
            if (complejidad.equals("S")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(3, 1) + 1), 3, 1);
            } else if (complejidad.equals("M")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(3, 2) + 1), 3, 2);
            } else if (complejidad.equals("C")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(3, 3) + 1), 3, 3);
            }
        }
        if (tipo.equals("CE")) {
            if (complejidad.equals("S")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(4, 1) + 1), 4, 1);
            } else if (complejidad.equals("M")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(4, 2) + 1), 4, 2);
            } else if (complejidad.equals("C")) {
                modeloC.setValueAt(((int) modeloC.getValueAt(4, 3) + 1), 4, 3);
            }
        }
    }
    public int calcularPFNA()
    {
        int total;
        total =((int) modeloC.getValueAt(0, 1) * 3)  + ((int) modeloC.getValueAt(0, 2) * 4) +((int) modeloC.getValueAt(0, 3) * 6) +
                ((int) modeloC.getValueAt(1, 1) * 4) + ((int) modeloC.getValueAt(1, 2) * 5) + ((int) modeloC.getValueAt(1, 3) * 7)+
                ((int) modeloC.getValueAt(2, 1) * 7) + ((int) modeloC.getValueAt(2, 2) * 10) + ((int) modeloC.getValueAt(2, 3) * 15) +
                ((int) modeloC.getValueAt(3, 1) * 5) + ((int) modeloC.getValueAt(3, 2) * 7) + ((int) modeloC.getValueAt(3, 3) * 10) + 
                ((int) modeloC.getValueAt(4, 1) * 3) + ((int) modeloC.getValueAt(4, 2) * 4) + ((int) modeloC.getValueAt(4, 3) * 6);
        return total;
    }
}

