/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sprint;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Ramso
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    VentanListarElementos ven = new VentanListarElementos();
    VentanaComplejidad vc = new VentanaComplejidad();
    ventanaSVA sva;
    
    public static ArrayList<Integer> datos = new ArrayList<>(16);
    boolean datosGuardados;
    float fa = 0, pfa = 0; // pfa = pf
    float esfuerzoC = 0, esfuerzoE = 0, esfuerzo, duracion;
    float duracionC = 0, duracionE = 0;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Practica Punto Función");
        setLocationRelativeTo(null);
        je2.setVisible(false);
        input2.setVisible(false);
        je3.setVisible(false);
        input3.setVisible(false);
        je4.setVisible(false);
        input4.setVisible(false);
        datosGuardados = false;
        panelEsfuerzo.setBorder(BorderFactory.createTitledBorder(
        BorderFactory.createEtchedBorder(), "Estimacion Esfuerzo", TitledBorder.LEFT,
        TitledBorder.TOP));
        panelDuracion.setBorder(BorderFactory.createTitledBorder(
        BorderFactory.createEtchedBorder(), "Estimación Duración", TitledBorder.LEFT,
        TitledBorder.TOP));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tiposE = new javax.swing.JComboBox<>();
        je1 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        je2 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        je5 = new javax.swing.JLabel();
        input5 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        je3 = new javax.swing.JLabel();
        input4 = new javax.swing.JTextField();
        je4 = new javax.swing.JLabel();
        btnComplejidad = new javax.swing.JButton();
        btnPFNA = new javax.swing.JButton();
        btncalcularFA = new javax.swing.JToggleButton();
        panelEsfuerzo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        caracteristicasProyectoEsfuerzo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        panelDuracion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        caracteristicasProyectoDuracion = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Elemento funcional:");

        tiposE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar tipo", "EE", "SE", "CE", "FLI", "FLE" }));
        tiposE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposEActionPerformed(evt);
            }
        });

        je1.setText("Nombre:");

        je2.setText("Nº Ficheros  Referenciados:");

        je5.setText("Nº  Datos Elementales:");

        je3.setText("Nº Ficheros  Relacionados");

        je4.setText("Nº Tipos de Registros");

        btnComplejidad.setText("Calcular Complejidad");
        btnComplejidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplejidadActionPerformed(evt);
            }
        });

        btnPFNA.setText("Calcular PFNA");
        btnPFNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPFNAActionPerformed(evt);
            }
        });

        btncalcularFA.setText("Calcular  SVA");
        btncalcularFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularFAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPFNA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btncalcularFA, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(je1)
                    .addComponent(jLabel1)
                    .addComponent(je2)
                    .addComponent(je3)
                    .addComponent(je4)
                    .addComponent(je5))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiposE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tiposE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je1)
                    .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(je2)
                    .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(je3)
                    .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je4)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(je5)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnComplejidad)
                    .addComponent(btnPFNA)
                    .addComponent(btncalcularFA))
                .addGap(20, 20, 20))
        );

        jLabel2.setText("Proyecto");

        caracteristicasProyectoEsfuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar caracterisita", "MF", "MR", "PC", "Multi", "3GL", "4GL", "GenAp", "Mantenimiento", "Nuevo", "MF-3GL", "MF-4GL", "MF-GenAp", "MR-3GL", "MR-4GL", "PC-3GL", "PC-4GL", "Multi-3GL", "Multi-4GL", "MF-3GL-Mantenimiento" }));
        caracteristicasProyectoEsfuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caracteristicasProyectoEsfuerzoActionPerformed(evt);
            }
        });

        jButton1.setText("Estimar esfuerzo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEsfuerzoLayout = new javax.swing.GroupLayout(panelEsfuerzo);
        panelEsfuerzo.setLayout(panelEsfuerzoLayout);
        panelEsfuerzoLayout.setHorizontalGroup(
            panelEsfuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsfuerzoLayout.createSequentialGroup()
                .addGroup(panelEsfuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEsfuerzoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(caracteristicasProyectoEsfuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEsfuerzoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelEsfuerzoLayout.setVerticalGroup(
            panelEsfuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsfuerzoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEsfuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caracteristicasProyectoEsfuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("Proyecto");

        caracteristicasProyectoDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar caracterisita", "PC", "Multi", "4GL", "Nuevo", "PC-4GL", "Multi-4GL", "PC-4GL-Nuevo", "Multi-4GL-Nuevo", "Otro" }));
        caracteristicasProyectoDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caracteristicasProyectoDuracionActionPerformed(evt);
            }
        });

        jButton2.setText("Estimar duración");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDuracionLayout = new javax.swing.GroupLayout(panelDuracion);
        panelDuracion.setLayout(panelDuracionLayout);
        panelDuracionLayout.setHorizontalGroup(
            panelDuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDuracionLayout.createSequentialGroup()
                .addGroup(panelDuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDuracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(caracteristicasProyectoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDuracionLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDuracionLayout.setVerticalGroup(
            panelDuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDuracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caracteristicasProyectoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        jMenu3.setText("Editar/Eliminar elemento");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenu2.setText("Salir");
        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelEsfuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEsfuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
        
        ven.setLocationRelativeTo(null);
        if (tiposE.getSelectedItem().toString().equals("EE")) {
            if (!input3.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                ven.setVisible(true);
                ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input3.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        if (tiposE.getSelectedItem().toString().matches("SE|CE")) {
            if (!input2.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                ven.setVisible(true);
                ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input2.getText());

            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        if (tiposE.getSelectedItem().toString().matches("FLI|FLE")) {
            if (!input4.getText().equals("") && !input1.getText().equals("") && !input5.getText().equals("")) {
                ven.setVisible(true);
                ven.introducirElemento(tiposE.getSelectedItem().toString(), input1.getText(), input5.getText(), input4.getText());

            } else {
                JOptionPane.showMessageDialog(null, "Asegurese de haber rellenado todos los campos.");
            }
        }
        JOptionPane.showMessageDialog(null, "Recuerde calcular la complejidad del elemento que acaba de añadir para que este se tenga en cuenta","Alert",JOptionPane.WARNING_MESSAGE);
        resetEntradas();

    }//GEN-LAST:event_btnAñadirActionPerformed

    private void tiposEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposEActionPerformed
        // TODO add your handling code here:

        if (tiposE.getSelectedItem().toString().equals("EE")) {
            je3.setVisible(true);
            input3.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);

            je4.setVisible(false);
            input4.setVisible(false);
        } else if (tiposE.getSelectedItem().toString().matches("SE|CE")) {
            je2.setVisible(true);
            input2.setVisible(true);

            je3.setVisible(false);
            input3.setVisible(false);
            je4.setVisible(false);
            input4.setVisible(false);
        } else if (tiposE.getSelectedItem().toString().matches("FLI|FLE")) {
            je4.setVisible(true);
            input4.setVisible(true);
            je2.setVisible(false);
            input2.setVisible(false);
            je3.setVisible(false);
            input3.setVisible(false);
        }

    }//GEN-LAST:event_tiposEActionPerformed

    private void btnComplejidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplejidadActionPerformed
        // TODO add your handling code here:
        String[] datos = ven.getElemento();
        String complejidad = "Sin valor.";
        int noElementos = Integer.parseInt(datos[0]);
        int noEntrada = Integer.parseInt(datos[1]);
        if (datos[2].equals("EE")) {
            if (noElementos >= 1 && noElementos <= 4) {
                if (noEntrada >= 0 && noEntrada <= 2) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 3) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 5 && noElementos <= 15) {
                if (noEntrada == 0 || noEntrada == 1) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada == 2) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 3) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 16) {
                if (noEntrada == 0 || noEntrada == 1) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 2) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            }
        } else if (datos[2].matches("SE|CE")) {
            if (noElementos >= 1 && noElementos <= 5) {
                if (noEntrada >= 0 && noEntrada <= 3) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 4) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 6 && noElementos <= 19) {
                if (noEntrada == 0 || noEntrada == 1) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada == 2 || noEntrada==3) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 4) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 20) {
                if (noEntrada == 0 || noEntrada == 1) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 2) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            }
        } else if (datos[2].matches("FLI|FLE")) {
            if (noElementos >= 1 && noElementos <= 19) {
                if (noEntrada >= 1 && noEntrada <= 5) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 6) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 20 && noElementos <= 50) {
                if (noEntrada >= 1) {
                    complejidad = "S";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 2 && noEntrada <= 5) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada >= 6) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            } else if (noElementos >= 51) {
                if (noEntrada >= 2) {
                    complejidad = "C";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                } else if (noEntrada == 1) {
                    complejidad = "M";
                    vc.añadirComplejidad(datos[2],complejidad);
                    vc.setVisible(true);
                }
            }
        }
        JOptionPane.showMessageDialog(null, "La complejidad del elemento funcional " + datos[2] + " es  " + complejidad);
    }//GEN-LAST:event_btnComplejidadActionPerformed

    private void btnPFNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPFNAActionPerformed
        if (vc.calcularPFNA() == 0) {
            JOptionPane.showMessageDialog(null, "Debe añadir y calcular la complejidad de los elementos si desea calcular el PFNA.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "El PFNA es igual a " + vc.calcularPFNA());
        }
    }//GEN-LAST:event_btnPFNAActionPerformed

    private void btncalcularFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularFAActionPerformed
        // TODO add your handling code here:
        sva = new ventanaSVA();
        sva.setVisible(true);
        fa = (float) (0.65 + (0.01 * this.datos.get(15)));
        pfa = vc.calcularPFNA() * fa;
    }//GEN-LAST:event_btncalcularFAActionPerformed

    private void caracteristicasProyectoEsfuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caracteristicasProyectoEsfuerzoActionPerformed
        // TODO add your handling code here:
        switch(caracteristicasProyectoEsfuerzo.getSelectedItem().toString()){
            case "MF": esfuerzoC = (float) 49.02; esfuerzoE = (float) 0.736; break;
            case "MR": esfuerzoC = (float) 78.88; esfuerzoE = (float) 0.646; break;
            case "PC": esfuerzoC = (float) 48.90; esfuerzoE = (float) 0.661; break;
            case "Multi": esfuerzoC = (float) 16.01; esfuerzoE = (float) 0.865; break;
            case "3GL": esfuerzoC = (float) 54.65; esfuerzoE = (float) 0.717; break;
            case "4GL": esfuerzoC = (float) 29.50; esfuerzoE = (float) 0.758; break;
            case "GenAp": esfuerzoC = (float) 68.11; esfuerzoE = (float) 0.660; break;
            case "Mantenimiento": esfuerzoC = (float) 52.58; esfuerzoE = (float) 0.683; break;
            case "Nuevo": esfuerzoC = (float) 39.05; esfuerzoE = (float) 0.731; break;
            case "MF-3GL": esfuerzoC = (float) 65.37; esfuerzoE = (float) 0.705; break;
            case "MF-4GL": esfuerzoC = (float) 52.09; esfuerzoE = (float) 0.640; break;
            case "MF-GenAp": esfuerzoC = (float) 65.68; esfuerzoE = (float) 0.692; break;
            case "MR-3GL": esfuerzoC = (float) 126.3; esfuerzoE = (float) 0.565; break;
            case "MR-4GL": esfuerzoC = (float) 62.35; esfuerzoE = (float) 0.694; break;
            case "PC-3GL": esfuerzoC = (float) 60.46; esfuerzoE = (float) 0.648; break;
            case "PC-4GL": esfuerzoC = (float) 36.48; esfuerzoE = (float) 0.694; break;
            case "Multi-3GL": esfuerzoC = (float) 19.82; esfuerzoE = (float) 0.666; break;
            case "Multi-4GL": esfuerzoC = (float) 6.49; esfuerzoE = (float) 0.983; break;
            case "MF-3GL-Mantenimiento": esfuerzoC = (float) 83.27; esfuerzoE = (float) 0.650; break;
        }
    }//GEN-LAST:event_caracteristicasProyectoEsfuerzoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Your code here! 19.82*(25.28)^0.666 170.354330682
        //float f = (float)Math.pow(25.28, 0.666);
        //float e = (float)19.82 * f;
        //System.out.println(e);
        esfuerzo = esfuerzoC * (float)Math.pow(pfa, esfuerzoE);
        //esfuerzo = (float) (19.82 * (float)Math.pow(25.28, 0.666));
        DecimalFormat df = new DecimalFormat("#.##");
        String s = df.format(esfuerzo);
        //System.out.println(df.format(esfuerzo)+" horas");
        JOptionPane.showMessageDialog(null, "La estimación, a partir de tamaño en PF, del esfuerzo"
                + " es de "+s+" horas");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void caracteristicasProyectoDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caracteristicasProyectoDuracionActionPerformed
        // TODO add your handling code here:
        switch(caracteristicasProyectoEsfuerzo.getSelectedItem().toString()){
            case "PC": duracionC = (float) 0.503; duracionE = (float) 0.409; break;
            case "Multi": duracionC = (float) 0.679; duracionE = (float) 0.341; break;
            case "4GL": duracionC = (float) 0.578; duracionE = (float) 0.393; break;
            case "Nuevo": duracionC = (float) 0.739; duracionE = (float) 0.359; break;
            case "PC-4GL": duracionC = (float) 0.348; duracionE = (float) 0.471; break;
            case "Multi-4GL": duracionC = (float) 0.366; duracionE = (float) 0.451; break;
            case "PC-4GL-Nuevo": duracionC = (float) 0.250; duracionE = (float) 0.515; break;
            case "Multi-4GL-Nuevo": duracionC = (float) 0.240; duracionE = (float) 0.518; break;
            case "Otro": duracionC = (float) 0.411; duracionE = (float) 0.328; break;
        }
    }//GEN-LAST:event_caracteristicasProyectoDuracionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //float f = (float)Math.pow(25.28, 0.666);
        //float e = (float)19.82 * f;
        //System.out.println(e);
        //duracion = duracionC * (float)Math.pow(pfa, duracionE);
        duracion = (float) (0.679 * (float)Math.pow(25.28, 0.341));
        DecimalFormat df = new DecimalFormat("#.##");
        String s = df.format(duracion);
        //System.out.println(df.format(duracion)+" horas");
        JOptionPane.showMessageDialog(null, "La estimación, a partir de tamaño en PF, del esfuerzo"
                + " es de "+s+" meses(1 persona)");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        ven.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnComplejidad;
    private javax.swing.JButton btnPFNA;
    private javax.swing.JToggleButton btncalcularFA;
    private javax.swing.JComboBox<String> caracteristicasProyectoDuracion;
    private javax.swing.JComboBox<String> caracteristicasProyectoEsfuerzo;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel je1;
    private javax.swing.JLabel je2;
    private javax.swing.JLabel je3;
    private javax.swing.JLabel je4;
    private javax.swing.JLabel je5;
    private javax.swing.JPanel panelDuracion;
    private javax.swing.JPanel panelEsfuerzo;
    private javax.swing.JComboBox<String> tiposE;
    // End of variables declaration//GEN-END:variables

    private void resetEntradas() {
        input1.setText("");
        input2.setText("");
        input3.setText("");
        input4.setText("");
        input5.setText("");
    }
}
